name: "âœ… CI: Agency"
on:
  workflow_call:

jobs:
  test-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"
          cache-dependency-path: agency/package-lock.json

      - name: Install & Build
        working-directory: ./agency
        env:
          NUXT_SANITY_AGENCY_PROJECT_ID: ${{ secrets.SANITY_AGENCY_PROJECT_ID }}
          NUXT_SANITY_AGENCY_DATASET: ${{ secrets.SANITY_AGENCY_DATASET }}
          NUXT_SANITY_AGENCY_STUDIO_APP_ID: ${{ secrets.SANITY_AGENCY_STUDIO_APP_ID }}
          NUXT_SANITY_AGENCY_API_VERSION: ${{ secrets.SANITY_AGENCY_API_VERSION }}
          NUXT_SANITY_REVALIDATE_SECRET: ${{ secrets.SANITY_REVALIDATE_SECRET }}
          NUXT_DEPLOY_SECRET: ${{ secrets.DEPLOY_SECRET }}
          NUXT_NITRO_CACHE_DIR: ${{ secrets.AGENCY_NITRO_CACHE_DIR }}
          NUXT_BASE_URL: ${{ secrets.AGENCY_BASE_URL }}

        run: |
          npm ci --legacy-peer-deps
          npm run build
